/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package howescape.scoutbookcsvprint;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;

/**
 *
 * @author Peter Maronda
 */
public class LabelPreviewPanel extends javax.swing.JPanel {

    private int xColumn = 0;
    private int yColumn = 0;
    private float labelWidth = 0.0f;
    /**
     * Creates new form LabelPreviewPanel
     */
    public LabelPreviewPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    public void paint(Graphics g) {
        Dimension panelSize = this.getSize();
        Double panelW = panelSize.getWidth();
        Double panelH = panelSize.getHeight();
        Double singleW = panelW / xColumn;
        Double singleH = panelH / yColumn;
        g.setColor(Color.BLACK);
        
        int singleHi = (int)Math.round(singleH);
        int singleWi = (int)Math.round(singleW);
        int labelNumber = 1;
        for (int y=0;y<yColumn;y++) {
            for (int x=0;x<xColumn;x++) {
                int singleHiLabel = (y*singleHi)+(singleHi/2);
                int singleWiLabel = (x*singleWi)+(singleWi/2);
                //g.setColor(Color.red);
                g.drawRect(x*singleWi, (y*singleHi), singleWi-2, singleHi-2);
                g.drawString(String.valueOf(labelNumber), singleWiLabel, singleHiLabel);
                labelNumber++;
            }
        }
        //g.setColor(Color.red);
        //g.fillRect(10,10,100,100);
    }

    public void setLabelParameters(int inXColumn, int inYRow, float label_width) {
        xColumn = inXColumn;
        yColumn = inYRow;
        labelWidth = label_width;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
